### ISSUE TITLE
el-get-bundle との組み合わせた場合の導入に関する問題

### ISSUE THREAD

**Issue by yewton** [tarao/el-get-lock#2]
## 概要

`el-get-bundle` と `el-get-lock` を組み合わせて導入すると、二回目移行の起動時に初期化が行われない場合があります。
## 詳細

`el-get.lock` が生成されていない状態で、 `(el-get-lock)` をした上で `(el-get-bundle)` を使ってパッケージのインストールを行うと、
`el-get-status-file` には `:checksum` が無く `:after` は `nil` の状態で保存されます。

この状態で再起動すると、初期化の際に https://github.com/dimitri/el-get/blob/master/el-get.el#L381 が呼ばれ、これは `el-get-status-file` から読み込まれます。
直前の https://github.com/dimitri/el-get/blob/master/el-get.el#L377-L378 この部分で `el-get-status-file` が更新されていれば問題ないのですが、 `el-get-bundle` のスコープで定義された `el-get-sources` ( `:after` と `:checksum` つき)と `el-get-status-file` の内容をマージするとき https://github.com/dimitri/el-get/blob/master/el-get-status.el#L364-L373 に、 `:checksum` の有無が異なるために更新が行われず、
結果として `:after nil` で `:checksum` が無い `source` を元に初期化が行われてしまいます。
## 対応案

`el-get-read-package-status-recipe` に `:checksum` をつけるようアドバイスする:

``` elisp
(defun el-get-lock-ad-read-package-status-recipe (orig-func &rest args)
  (let* ((recipe (apply orig-func args))
         (package (first args))
         (checksum (el-get-checksum package)))
    (if (plist-get recipe :checksum)
        recipe
      (plist-put recipe :checksum checksum))))
(advice-add #'el-get-read-package-status-recipe :around #'el-get-lock-ad-read-package-status-recipe)
```

もしくは、`el-get-status-file` に `checksum` も記録するように hook を仕込む:

``` elisp
(defun el-get-lock-save-installed-version-to-status (package)
  (let* ((name (if (stringp package) package (el-get-source-name package)))
         (checksum (ignore-errors (el-get-checksum name)))
         (version (and checksum (list :checksum checksum)))
         (recipe (el-get-package-def name)))
    (when (and version (not (plist-get recipe :checksum)))
      (el-get-save-package-status name "installed" (append version recipe)))))
(add-hook 'el-get-post-install-hooks #'el-get-lock-save-installed-version-to-status)
```

どちらかで対応できそうでした。

**Comment by tarao** [comment]
ご報告および調査ありがとうございます。

`el-get-update`の際にも同様の問題があり、元々はel-get本体側の変更でうまくいかなくなっていたという認識でしたが、いろいろ精査したところ、仰る通り`el-get-status-file`の状態に`:checksum`が正しく反映されないのが原因とみてよさそうでした。`el-get-update`の場合にも適用されるように`el-get-post-update-hooks`にも登録する、`el-get-update`の際にはel-get-lockが`:checkout`を強制的に置き換えることでアップデートするのでそれが`el-get-status-file`に入ってしまうのを防ぐ、という点を加えれば、@yewtonさんの提案ほぼそのままでうまくいきそうでした。以下のような具合です。

``` lisp
(defun el-get-lock-save-installed-version-to-status (package)
  (let* ((name (if (stringp package) package (el-get-source-name package)))
         (checksum (ignore-errors (el-get-checksum name)))
         (recipe (el-get-package-def name)))
    (when (and checksum (not (plist-get recipe :checksum)))
      (let* ((recipe (plist-put recipe :checksum checksum))
             (recipe (plist-put recipe :checkout nil)))
        (el-get-save-package-status name "installed" recipe)))))
(add-hook 'el-get-post-install-hooks #'el-get-lock-save-installed-version-to-status)
(add-hook 'el-get-post-update-hooks #'el-get-lock-save-installed-version-to-status)
```

つきましては、上記コードを加えるpull requestをしていただけないでしょうか? (せっかく修正案まで作っていただいたので、@yewtonさんをauthorとして取り込みたいとおもいます。)

**Comment by tarao** [comment]
`el-get-lock-unlock`で明示的にバージョン固定対象から外していた場合の考慮が漏れていたので、以下のようにした方がよいですね。(あと`:checkout`を潰す方法が上のはちょっと雑だったので直してます。)

``` lisp
(defun el-get-lock-save-installed-version-to-status (package)
  (let* ((name (if (stringp package) package (el-get-source-name package)))
         (checksum (ignore-errors (el-get-checksum name)))
         (recipe (el-get-package-def name))
         (unlocked (memq (intern name) el-get-lock-unlocked-packages)))
    (when (and checksum (not (plist-get recipe :checksum)) (not unlocked))
      (setq recipe (plist-put recipe :checksum checksum)
            recipe
            (loop for (k v) on recipe by #'cddr
                  unless (eq k :checkout)
                  collect k and collect v))
      (el-get-save-package-status name "installed" recipe))))
(add-hook 'el-get-post-install-hooks #'el-get-lock-save-installed-version-to-status)
(add-hook 'el-get-post-update-hooks #'el-get-lock-save-installed-version-to-status)
```
